export enum Status {
  APPLICANT = 'APPLICANT',
  SHORTLISTED = 'SHORTLISTED',
  TALENT_POOL = 'TALENT POOL',
  ASSESSMENT = 'ASSESSMENT',
  INTERVIEW = 'INTERVIEW',
  REFCHECK = 'REFERENCE CHECK',
  OFFERING = 'OFFERING',
  MCU = 'MCU',
  AGREEMENT = 'AGREEMENT',
  BOARDING = 'BOARDING',
}
